data:
  raw:
    file_scraped: "../data/raw/vscode_extensions_scraped_0825.csv"
    file_verified: "../data/raw/VSCode Extensions_Verified.csv"
    file_vulnerable: "../data/raw/VSCode Extensions_Vulnerabilities.csv"
    file_ext_repo: "../data/raw/extensions_repos_full.csv"
  clean:
    file_scrap_cleaned: "../data/clean/extensions_scrap_cleaned.csv"
    file_data_cleaned: "../data/clean/extensions_data_cleaned.csv"
    file_eda_cleaned: "../data/clean/extensions_eda_cleaned.csv"
model:
  preprocessing:
    file_ohe: "../model/one_hot_encoder.pkl"
